/**
 * Enum containing languages
 */
export enum Language {

  UNSPECIFIED = '???',

  ENGLISH = 'English',
  GERMAN = 'German',
  SPANISH = 'Spanish',

  //

  AFRIKAANS = 'Afrikaans',
  ARABIC = 'Arabic',
  BANGLA = 'Bangla',
  BOSNIAN_LATIN = 'Bosnian (Latin)',
  BULGARIAN = 'Bulgarian',
  CANTONESE = 'Cantonese',
  CATALAN = 'Catalan',
  CHINESE_SIMPLIFIED = 'Chinese (simplified)',
  CHINESE_TRADITIONAL = 'Chinese (traditional)',

  CROATION = 'Croatian',
  CZECH = 'Czech',
  DANISH = 'Danish',
  DUTCH = 'Dutch',
  ESTONIAN = 'Estonian',
  FIJAN = 'Fijian',
  FILIPINO = 'Filipino',
  FINNISH = 'Finnish',
  FRENCH = 'French',
  GREEK = 'Greek',
  HAITIAN_CREOLE = 'Haitian Creole',
  HEBREW = 'Hebrew',
  HINDI = 'Hindi',
  HMONG_DAW = 'Hmong Daw',
  HUNGARIAN = 'Hungarian',
  ICELANDIC = 'Icelandic',
  INDONESIAN = 'Indonesian',
  ITALIAN = 'Italian',
  JAPANESE = 'Japanese',
  KISWAHILI = 'Kiswahili',
  KLINGON = 'Klingon',
  KLINGON_PLQAD = 'Klingon (plqaD)',
  KOREAN = 'Korean',
  LATVIAN = 'Latvian',
  LITHUANIAN = 'Lithuanian',
  MALAGASY = 'Malagasy',
  MALAY = 'Malay',
  MALTESE = 'Maltese',
  NORWEGIAN = 'Norwegian',
  PERSIAN = 'Persian',
  POLISH = 'Polish',
  PORTUGUESE = 'Portuguese',
  QUERETARO_OTOMI = 'Queretaro Otomi',
  ROMANIAN = 'Romanian',
  RUSSION = 'Russian',
  SAMOAN = 'Samoan',
  SERBIAN_CYRILLIC = 'Serbian (Cyrillic)',
  SERBIAN_LATIN = 'Serbian (Latin)',
  SLOVAK = 'Slovak',
  SLOVENIAN = 'Slovenian',
  SWEDISH = 'Swedish',
  TAHITIAN = 'Tahitian',
  TAMIL = 'Tamil',
  TELUGU = 'Telugu',
  THAI = 'Thai',
  TONGAN = 'Tongan',
  TURKISH = 'Turkish',
  UKRAINIAN = 'Ukrainian',
  URDU = 'Urdu',
  VIETNAMESE = 'Vietnamese',
  WELSH = 'Welsh',
  YUCATEC_MAYA = 'Yucatec Maya',
}
